# Generated by Django 3.1.4 on 2021-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='predecessor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
